# Generated by Django 4.0.4 on 2022-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0002_medlpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlpicture',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medlpicture',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medlpicture',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
