# Generated by Django 4.0.4 on 2022-04-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0003_medlpicture_author_alter_medlpicture_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedlTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
