# Generated by Django 4.0.4 on 2022-04-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0004_medltags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedlTags',
            new_name='MedlTag',
        ),
    ]
