# Generated by Django 4.0.4 on 2022-04-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0005_rename_medltags_medltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlpicture',
            name='tags',
            field=models.ManyToManyField(to='Function.medltag'),
        ),
        migrations.AlterField(
            model_name='medlpicture',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Function.medlmember'),
        ),
        migrations.AlterField(
            model_name='medltag',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Function.medlmember'),
        ),
    ]
