# Generated by Django 4.0.4 on 2022-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0006_medlpicture_tags_alter_medlpicture_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlpicture',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medltag',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
