# Generated by Django 4.0.4 on 2022-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0008_alter_medlpicture_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlpicture',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medlpicture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Function.medltag'),
        ),
    ]
