# Generated by Django 4.0.4 on 2022-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0009_alter_medlpicture_name_alter_medlpicture_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medltag',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
